# build go binary (linux amd64) and release on github actions

on:
  push:
    tags:
      - "*"

permissions:
  contents: write
  packages: write
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: mkdir ${HOME}/go
      - run: GOPATH="${HOME}/go" go install github.com/ssig33/gdrive@latest
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: "${HOME}/go/bin/gdrive"


